services:
  - type: web
    name: partnership-goals-backend
    env: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /docs
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: partnership-data
      mountPath: /app/backend/data
      sizeGB: 1 